### ISSUE TITLE
Prefix by Swift Version by Default

### ISSUE THREAD

**Issue by fabb** [blender/Rome#127]
## Enhancement Suggestion

Currently it‘s the responsibility of the client to add a prefix with the correct Swift version. Would it be thinkable to make Rome do that by default without having to provide the prefix manually? This other caching tool does it as well: https://github.com/Wolox/carthage_cache

**Comment by blender** [comment]
Off the top of my head I would say I'm not very keen on embedding any swift specific logic since the cache prefix is global for all frameworks even if objective c.

Also if this would be implemented then I would expect Rome to check that all frameworks are built with the same version or are objc frameworks. 

I'm not so keen on imposing all these restrictions just to avoid some discipline on the consumer side.

**Comment by fabb** [comment]
Ok I see. Then maybe we‘ll just write guidelines for everyone on our distributed teams to follow the same prefix conventions. We have around 100 ios devs working on different products, but with partially overlapping dependencies, would be nice if we could share a common Rome cache server.

**Comment by blender** [comment]
Since you're using Rome to download you can just use the current swift version like this:

```
--cache-prefix=`swift --version | head -1 | sed 's/.*\((.*)\).*/\1/' | tr -d "()" | tr " " "-"`
```

**Comment by fabb** [comment]
Btw. Swift 5 will NOT make this unnecessary. While Swift 5 provides ABI stability, it does NOT provide module stability which would also be be needed for supporting precompiled Swift frameworks of other Swift versions.
https://forums.swift.org/t/plan-for-module-stability/14551

**Comment by blender** [comment]
@fabb  I have read the issue but I don't see how this matters? 

If any that thread is another reason not to derive the cache name automatically since multiple compiler versions can share the same binary.
